import dataclasses
from mujoco.mjx._src import types
from mujoco.mjx.warp import ffi_helper
import mujoco_warp as mjwarp
from mujoco_warp._src import types as mjwarp_types
import warp as wp

_m = mjwarp.Model(
    **{f.name: None for f in dataclasses.fields(mjwarp.Model) if f.init}
)
_d = mjwarp.Data(
    **{f.name: None for f in dataclasses.fields(mjwarp.Data) if f.init}
)


def _forward(
    # Model
    nv: int,
    nu: int,
    na: int,
    nbody: int,
    njnt: int,
    ngeom: int,
    nsite: int,
    ncam: int,
    nlight: int,
    neq: int,
    nmocap: int,
    ngravcomp: int,
    nM: int,
    ntendon: int,
    nlsp: int,
    opt__timestep: float,
    opt__impratio: float,
    opt__tolerance: float,
    opt__ls_tolerance: float,
    opt__gravity: wp.vec3,
    opt__cone: int,
    opt__solver: int,
    opt__iterations: int,
    opt__ls_iterations: int,
    opt__disableflags: int,
    opt__is_sparse: bool,
    opt__ls_parallel: bool,
    opt__wind: wp.vec3,
    opt__density: float,
    opt__viscosity: float,
    stat__meaninertia: float,
    qpos0: wp.array2d(dtype=float),
    qpos_spring: wp.array2d(dtype=float),
    qM_fullm_i: wp.array(dtype=int),
    qM_fullm_j: wp.array(dtype=int),
    qM_mulm_i: wp.array(dtype=int),
    qM_mulm_j: wp.array(dtype=int),
    qM_madr_ij: wp.array(dtype=int),
    qLD_updates: tuple[wp.array(dtype=wp.vec3i), ...],
    M_rownnz: wp.array(dtype=int),
    M_rowadr: wp.array(dtype=int),
    mapM2M: wp.array(dtype=int),
    qM_tiles: tuple[mjwarp_types.TileSet, ...],
    body_tree: tuple[wp.array(dtype=int), ...],
    body_parentid: wp.array(dtype=int),
    body_rootid: wp.array(dtype=int),
    body_jntnum: wp.array(dtype=int),
    body_jntadr: wp.array(dtype=int),
    body_dofnum: wp.array(dtype=int),
    body_dofadr: wp.array(dtype=int),
    body_pos: wp.array2d(dtype=wp.vec3),
    body_quat: wp.array2d(dtype=wp.quat),
    body_ipos: wp.array2d(dtype=wp.vec3),
    body_iquat: wp.array2d(dtype=wp.quat),
    body_mass: wp.array2d(dtype=float),
    body_subtreemass: wp.array2d(dtype=float),
    subtree_mass: wp.array2d(dtype=float),
    body_inertia: wp.array2d(dtype=wp.vec3),
    body_invweight0: wp.array3d(dtype=float),
    body_gravcomp: wp.array2d(dtype=float),
    jnt_type: wp.array(dtype=int),
    jnt_qposadr: wp.array(dtype=int),
    jnt_dofadr: wp.array(dtype=int),
    jnt_bodyid: wp.array(dtype=int),
    jnt_actfrclimited: wp.array(dtype=bool),
    jnt_solref: wp.array2d(dtype=wp.vec2),
    jnt_solimp: wp.array2d(dtype=mjwarp_types.vec5),
    jnt_pos: wp.array2d(dtype=wp.vec3),
    jnt_axis: wp.array2d(dtype=wp.vec3),
    jnt_stiffness: wp.array2d(dtype=float),
    jnt_range: wp.array3d(dtype=float),
    jnt_actfrcrange: wp.array2d(dtype=wp.vec2),
    jnt_margin: wp.array2d(dtype=float),
    jnt_limited_slide_hinge_adr: wp.array(dtype=int),
    jnt_limited_ball_adr: wp.array(dtype=int),
    jnt_actgravcomp: wp.array(dtype=int),
    dof_bodyid: wp.array(dtype=int),
    dof_jntid: wp.array(dtype=int),
    dof_parentid: wp.array(dtype=int),
    dof_Madr: wp.array(dtype=int),
    dof_armature: wp.array2d(dtype=float),
    dof_damping: wp.array2d(dtype=float),
    dof_invweight0: wp.array2d(dtype=float),
    dof_frictionloss: wp.array2d(dtype=float),
    dof_solimp: wp.array2d(dtype=mjwarp_types.vec5),
    dof_solref: wp.array2d(dtype=wp.vec2),
    dof_tri_row: wp.array(dtype=int),
    dof_tri_col: wp.array(dtype=int),
    geom_type: wp.array(dtype=int),
    geom_bodyid: wp.array(dtype=int),
    geom_rbound: wp.array2d(dtype=float),
    geom_pos: wp.array2d(dtype=wp.vec3),
    geom_quat: wp.array2d(dtype=wp.quat),
    geom_margin: wp.array2d(dtype=float),
    site_bodyid: wp.array(dtype=int),
    site_pos: wp.array2d(dtype=wp.vec3),
    site_quat: wp.array2d(dtype=wp.quat),
    cam_mode: wp.array(dtype=int),
    cam_bodyid: wp.array(dtype=int),
    cam_targetbodyid: wp.array(dtype=int),
    cam_pos: wp.array2d(dtype=wp.vec3),
    cam_quat: wp.array2d(dtype=wp.quat),
    cam_poscom0: wp.array2d(dtype=wp.vec3),
    cam_pos0: wp.array2d(dtype=wp.vec3),
    cam_mat0: wp.array2d(dtype=wp.mat33),
    cam_fovy: wp.array(dtype=float),
    cam_resolution: wp.array(dtype=wp.vec2i),
    cam_sensorsize: wp.array(dtype=wp.vec2),
    cam_intrinsic: wp.array(dtype=wp.vec4),
    light_mode: wp.array(dtype=int),
    light_bodyid: wp.array(dtype=int),
    light_targetbodyid: wp.array(dtype=int),
    light_pos: wp.array2d(dtype=wp.vec3),
    light_dir: wp.array2d(dtype=wp.vec3),
    light_poscom0: wp.array2d(dtype=wp.vec3),
    light_pos0: wp.array2d(dtype=wp.vec3),
    light_dir0: wp.array2d(dtype=wp.vec3),
    eq_obj1id: wp.array(dtype=int),
    eq_obj2id: wp.array(dtype=int),
    eq_objtype: wp.array(dtype=int),
    eq_solref: wp.array2d(dtype=wp.vec2),
    eq_solimp: wp.array2d(dtype=mjwarp_types.vec5),
    eq_data: wp.array2d(dtype=mjwarp_types.vec11),
    eq_connect_adr: wp.array(dtype=int),
    eq_wld_adr: wp.array(dtype=int),
    eq_jnt_adr: wp.array(dtype=int),
    eq_ten_adr: wp.array(dtype=int),
    actuator_moment_tiles_nv: tuple[mjwarp_types.TileSet, ...],
    actuator_moment_tiles_nu: tuple[mjwarp_types.TileSet, ...],
    actuator_trntype: wp.array(dtype=int),
    actuator_dyntype: wp.array(dtype=int),
    actuator_gaintype: wp.array(dtype=int),
    actuator_biastype: wp.array(dtype=int),
    actuator_trnid: wp.array(dtype=wp.vec2i),
    actuator_actadr: wp.array(dtype=int),
    actuator_actnum: wp.array(dtype=int),
    actuator_ctrllimited: wp.array(dtype=bool),
    actuator_forcelimited: wp.array(dtype=bool),
    actuator_dynprm: wp.array2d(dtype=mjwarp_types.vec10f),
    actuator_gainprm: wp.array2d(dtype=mjwarp_types.vec10f),
    actuator_biasprm: wp.array2d(dtype=mjwarp_types.vec10f),
    actuator_ctrlrange: wp.array2d(dtype=wp.vec2),
    actuator_forcerange: wp.array2d(dtype=wp.vec2),
    actuator_gear: wp.array2d(dtype=wp.spatial_vector),
    nxn_geom_pair: wp.array(dtype=wp.vec2i),
    nxn_pairid: wp.array(dtype=int),
    condim_max: int,
    tendon_adr: wp.array(dtype=int),
    tendon_num: wp.array(dtype=int),
    tendon_limited_adr: wp.array(dtype=int),
    tendon_solref_lim: wp.array2d(dtype=wp.vec2),
    tendon_solimp_lim: wp.array2d(dtype=mjwarp_types.vec5),
    tendon_range: wp.array2d(dtype=wp.vec2),
    tendon_margin: wp.array2d(dtype=float),
    tendon_length0: wp.array2d(dtype=float),
    tendon_invweight0: wp.array2d(dtype=float),
    wrap_objid: wp.array(dtype=int),
    wrap_prm: wp.array(dtype=float),
    wrap_type: wp.array(dtype=int),
    tendon_jnt_adr: wp.array(dtype=int),
    tendon_site_pair_adr: wp.array(dtype=int),
    ten_wrapadr_site: wp.array(dtype=int),
    ten_wrapnum_site: wp.array(dtype=int),
    wrap_jnt_adr: wp.array(dtype=int),
    wrap_site_adr: wp.array(dtype=int),
    wrap_site_pair_adr: wp.array(dtype=int),
    sensor_type: wp.array(dtype=int),
    sensor_datatype: wp.array(dtype=int),
    sensor_objtype: wp.array(dtype=int),
    sensor_objid: wp.array(dtype=int),
    sensor_reftype: wp.array(dtype=int),
    sensor_refid: wp.array(dtype=int),
    sensor_adr: wp.array(dtype=int),
    sensor_cutoff: wp.array(dtype=float),
    sensor_pos_adr: wp.array(dtype=int),
    sensor_vel_adr: wp.array(dtype=int),
    sensor_acc_adr: wp.array(dtype=int),
    sensor_subtree_vel: bool,
    sensor_rne_postconstraint: bool,
    mocap_bodyid: wp.array(dtype=int),
    # Data
    nconmax: int,
    njmax: int,
    ncon: wp.array(dtype=int),
    time: wp.array(dtype=float),
    qpos: wp.array2d(dtype=float),
    qvel: wp.array2d(dtype=float),
    act: wp.array2d(dtype=float),
    qacc_warmstart: wp.array2d(dtype=float),
    ctrl: wp.array2d(dtype=float),
    qfrc_applied: wp.array2d(dtype=float),
    xfrc_applied: wp.array2d(dtype=wp.spatial_vector),
    eq_active: wp.array2d(dtype=bool),
    mocap_pos: wp.array2d(dtype=wp.vec3),
    mocap_quat: wp.array2d(dtype=wp.quat),
    qLD: wp.array3d(dtype=float),
    qLDiagInv: wp.array2d(dtype=float),
    qfrc_fluid: wp.array2d(dtype=float),
    qacc_smooth: wp.array2d(dtype=float),
    contact__dist: wp.array(dtype=float),
    contact__pos: wp.array(dtype=wp.vec3),
    contact__frame: wp.array(dtype=wp.mat33),
    contact__includemargin: wp.array(dtype=float),
    contact__friction: wp.array(dtype=mjwarp_types.vec5),
    contact__solref: wp.array(dtype=wp.vec2),
    contact__solreffriction: wp.array(dtype=wp.vec2),
    contact__solimp: wp.array(dtype=mjwarp_types.vec5),
    contact__dim: wp.array(dtype=int),
    contact__geom: wp.array(dtype=wp.vec2i),
    contact__worldid: wp.array(dtype=int),
    efc__mv: wp.array2d(dtype=float),
    sap_cumulative_sum: wp.array(dtype=int),
    sap_segment_index: wp.array(dtype=int),
    ne: wp.array(dtype=int),
    ne_connect: wp.array(dtype=int),
    ne_weld: wp.array(dtype=int),
    ne_jnt: wp.array(dtype=int),
    ne_ten: wp.array(dtype=int),
    nf: wp.array(dtype=int),
    nl: wp.array(dtype=int),
    nefc: wp.array(dtype=int),
    fluid_applied: wp.array2d(dtype=wp.spatial_vector),
    qacc: wp.array2d(dtype=float),
    act_dot: wp.array2d(dtype=float),
    xpos: wp.array2d(dtype=wp.vec3),
    xquat: wp.array2d(dtype=wp.quat),
    xmat: wp.array2d(dtype=wp.mat33),
    xipos: wp.array2d(dtype=wp.vec3),
    ximat: wp.array2d(dtype=wp.mat33),
    xanchor: wp.array2d(dtype=wp.vec3),
    xaxis: wp.array2d(dtype=wp.vec3),
    geom_xpos: wp.array2d(dtype=wp.vec3),
    geom_xmat: wp.array2d(dtype=wp.mat33),
    site_xpos: wp.array2d(dtype=wp.vec3),
    site_xmat: wp.array2d(dtype=wp.mat33),
    cam_xpos: wp.array2d(dtype=wp.vec3),
    cam_xmat: wp.array2d(dtype=wp.mat33),
    light_xpos: wp.array2d(dtype=wp.vec3),
    light_xdir: wp.array2d(dtype=wp.vec3),
    subtree_com: wp.array2d(dtype=wp.vec3),
    cdof: wp.array2d(dtype=wp.spatial_vector),
    cinert: wp.array2d(dtype=mjwarp_types.vec10),
    actuator_length: wp.array2d(dtype=float),
    actuator_moment: wp.array3d(dtype=float),
    crb: wp.array2d(dtype=mjwarp_types.vec10),
    qM: wp.array3d(dtype=float),
    ten_velocity: wp.array2d(dtype=float),
    actuator_velocity: wp.array2d(dtype=float),
    cvel: wp.array2d(dtype=wp.spatial_vector),
    cdof_dot: wp.array2d(dtype=wp.spatial_vector),
    qfrc_bias: wp.array2d(dtype=float),
    qfrc_spring: wp.array2d(dtype=float),
    qfrc_damper: wp.array2d(dtype=float),
    qfrc_gravcomp: wp.array2d(dtype=float),
    qfrc_passive: wp.array2d(dtype=float),
    subtree_linvel: wp.array2d(dtype=wp.vec3),
    subtree_angmom: wp.array2d(dtype=wp.vec3),
    subtree_bodyvel: wp.array2d(dtype=wp.spatial_vector),
    actuator_force: wp.array2d(dtype=float),
    qfrc_actuator: wp.array2d(dtype=float),
    qfrc_smooth: wp.array2d(dtype=float),
    qfrc_constraint: wp.array2d(dtype=float),
    contact__efc_address: wp.array2d(dtype=int),
    efc__worldid: wp.array(dtype=int),
    efc__id: wp.array(dtype=int),
    efc__J: wp.array2d(dtype=float),
    efc__pos: wp.array(dtype=float),
    efc__margin: wp.array(dtype=float),
    efc__D: wp.array(dtype=float),
    efc__aref: wp.array(dtype=float),
    efc__frictionloss: wp.array(dtype=float),
    efc__force: wp.array(dtype=float),
    efc__Jaref: wp.array(dtype=float),
    efc__Ma: wp.array2d(dtype=float),
    efc__grad: wp.array2d(dtype=float),
    efc__grad_dot: wp.array(dtype=float),
    efc__Mgrad: wp.array2d(dtype=float),
    efc__search: wp.array2d(dtype=float),
    efc__search_dot: wp.array(dtype=float),
    efc__gauss: wp.array(dtype=float),
    efc__cost: wp.array(dtype=float),
    efc__prev_cost: wp.array(dtype=float),
    efc__solver_niter: wp.array(dtype=int),
    efc__active: wp.array(dtype=bool),
    efc__gtol: wp.array(dtype=float),
    efc__jv: wp.array(dtype=float),
    efc__quad: wp.array(dtype=wp.vec3),
    efc__quad_gauss: wp.array(dtype=wp.vec3),
    efc__h: wp.array3d(dtype=float),
    efc__alpha: wp.array(dtype=float),
    efc__prev_grad: wp.array2d(dtype=float),
    efc__prev_Mgrad: wp.array2d(dtype=float),
    efc__beta: wp.array(dtype=float),
    efc__beta_num: wp.array(dtype=float),
    efc__beta_den: wp.array(dtype=float),
    efc__done: wp.array(dtype=bool),
    efc__ls_done: wp.array(dtype=bool),
    efc__p0: wp.array(dtype=wp.vec3),
    efc__lo: wp.array(dtype=wp.vec3),
    efc__lo_alpha: wp.array(dtype=float),
    efc__hi: wp.array(dtype=wp.vec3),
    efc__hi_alpha: wp.array(dtype=float),
    efc__lo_next: wp.array(dtype=wp.vec3),
    efc__lo_next_alpha: wp.array(dtype=float),
    efc__hi_next: wp.array(dtype=wp.vec3),
    efc__hi_next_alpha: wp.array(dtype=float),
    efc__mid: wp.array(dtype=wp.vec3),
    efc__mid_alpha: wp.array(dtype=float),
    efc__cost_candidate: wp.array2d(dtype=float),
    efc__quad_total_candidate: wp.array2d(dtype=wp.vec3),
    efc__u: wp.array(dtype=mjwarp_types.vec6),
    efc__uu: wp.array(dtype=float),
    efc__uv: wp.array(dtype=float),
    efc__vv: wp.array(dtype=float),
    efc__condim: wp.array(dtype=int),
    sap_projection_lower: wp.array2d(dtype=float),
    sap_projection_upper: wp.array2d(dtype=float),
    sap_sort_index: wp.array2d(dtype=int),
    sap_range: wp.array2d(dtype=int),
    collision_pair: wp.array(dtype=wp.vec2i),
    collision_pairid: wp.array(dtype=int),
    collision_worldid: wp.array(dtype=int),
    ncollision: wp.array(dtype=int),
    cacc: wp.array2d(dtype=wp.spatial_vector),
    cfrc_int: wp.array2d(dtype=wp.spatial_vector),
    cfrc_ext: wp.array2d(dtype=wp.spatial_vector),
    ten_length: wp.array2d(dtype=float),
    ten_J: wp.array3d(dtype=float),
    ten_wrapadr: wp.array2d(dtype=int),
    ten_wrapnum: wp.array2d(dtype=int),
    wrap_obj: wp.array2d(dtype=wp.vec2i),
    wrap_xpos: wp.array2d(dtype=wp.spatial_vector),
    sensordata: wp.array2d(dtype=float),
):
  _m.M_rowadr = M_rowadr
  _m.M_rownnz = M_rownnz
  _m.actuator_actadr = actuator_actadr
  _m.actuator_actnum = actuator_actnum
  _m.actuator_biasprm = actuator_biasprm
  _m.actuator_biastype = actuator_biastype
  _m.actuator_ctrllimited = actuator_ctrllimited
  _m.actuator_ctrlrange = actuator_ctrlrange
  _m.actuator_dynprm = actuator_dynprm
  _m.actuator_dyntype = actuator_dyntype
  _m.actuator_forcelimited = actuator_forcelimited
  _m.actuator_forcerange = actuator_forcerange
  _m.actuator_gainprm = actuator_gainprm
  _m.actuator_gaintype = actuator_gaintype
  _m.actuator_gear = actuator_gear
  _m.actuator_moment_tiles_nu = actuator_moment_tiles_nu
  _m.actuator_moment_tiles_nv = actuator_moment_tiles_nv
  _m.actuator_trnid = actuator_trnid
  _m.actuator_trntype = actuator_trntype
  _m.body_dofadr = body_dofadr
  _m.body_dofnum = body_dofnum
  _m.body_gravcomp = body_gravcomp
  _m.body_inertia = body_inertia
  _m.body_invweight0 = body_invweight0
  _m.body_ipos = body_ipos
  _m.body_iquat = body_iquat
  _m.body_jntadr = body_jntadr
  _m.body_jntnum = body_jntnum
  _m.body_mass = body_mass
  _m.body_parentid = body_parentid
  _m.body_pos = body_pos
  _m.body_quat = body_quat
  _m.body_rootid = body_rootid
  _m.body_subtreemass = body_subtreemass
  _m.body_tree = body_tree
  _m.cam_bodyid = cam_bodyid
  _m.cam_fovy = cam_fovy
  _m.cam_intrinsic = cam_intrinsic
  _m.cam_mat0 = cam_mat0
  _m.cam_mode = cam_mode
  _m.cam_pos = cam_pos
  _m.cam_pos0 = cam_pos0
  _m.cam_poscom0 = cam_poscom0
  _m.cam_quat = cam_quat
  _m.cam_resolution = cam_resolution
  _m.cam_sensorsize = cam_sensorsize
  _m.cam_targetbodyid = cam_targetbodyid
  _m.condim_max = condim_max
  _m.dof_Madr = dof_Madr
  _m.dof_armature = dof_armature
  _m.dof_bodyid = dof_bodyid
  _m.dof_damping = dof_damping
  _m.dof_frictionloss = dof_frictionloss
  _m.dof_invweight0 = dof_invweight0
  _m.dof_jntid = dof_jntid
  _m.dof_parentid = dof_parentid
  _m.dof_solimp = dof_solimp
  _m.dof_solref = dof_solref
  _m.dof_tri_col = dof_tri_col
  _m.dof_tri_row = dof_tri_row
  _m.eq_connect_adr = eq_connect_adr
  _m.eq_data = eq_data
  _m.eq_jnt_adr = eq_jnt_adr
  _m.eq_obj1id = eq_obj1id
  _m.eq_obj2id = eq_obj2id
  _m.eq_objtype = eq_objtype
  _m.eq_solimp = eq_solimp
  _m.eq_solref = eq_solref
  _m.eq_ten_adr = eq_ten_adr
  _m.eq_wld_adr = eq_wld_adr
  _m.geom_bodyid = geom_bodyid
  _m.geom_margin = geom_margin
  _m.geom_pos = geom_pos
  _m.geom_quat = geom_quat
  _m.geom_rbound = geom_rbound
  _m.geom_type = geom_type
  _m.jnt_actfrclimited = jnt_actfrclimited
  _m.jnt_actfrcrange = jnt_actfrcrange
  _m.jnt_actgravcomp = jnt_actgravcomp
  _m.jnt_axis = jnt_axis
  _m.jnt_bodyid = jnt_bodyid
  _m.jnt_dofadr = jnt_dofadr
  _m.jnt_limited_ball_adr = jnt_limited_ball_adr
  _m.jnt_limited_slide_hinge_adr = jnt_limited_slide_hinge_adr
  _m.jnt_margin = jnt_margin
  _m.jnt_pos = jnt_pos
  _m.jnt_qposadr = jnt_qposadr
  _m.jnt_range = jnt_range
  _m.jnt_solimp = jnt_solimp
  _m.jnt_solref = jnt_solref
  _m.jnt_stiffness = jnt_stiffness
  _m.jnt_type = jnt_type
  _m.light_bodyid = light_bodyid
  _m.light_dir = light_dir
  _m.light_dir0 = light_dir0
  _m.light_mode = light_mode
  _m.light_pos = light_pos
  _m.light_pos0 = light_pos0
  _m.light_poscom0 = light_poscom0
  _m.light_targetbodyid = light_targetbodyid
  _m.mapM2M = mapM2M
  _m.mocap_bodyid = mocap_bodyid
  _m.nM = nM
  _m.na = na
  _m.nbody = nbody
  _m.ncam = ncam
  _m.neq = neq
  _m.ngeom = ngeom
  _m.ngravcomp = ngravcomp
  _m.njnt = njnt
  _m.nlight = nlight
  _m.nlsp = nlsp
  _m.nmocap = nmocap
  _m.nsite = nsite
  _m.ntendon = ntendon
  _m.nu = nu
  _m.nv = nv
  _m.nxn_geom_pair = nxn_geom_pair
  _m.nxn_pairid = nxn_pairid
  _m.opt.cone = opt__cone
  _m.opt.density = opt__density
  _m.opt.disableflags = opt__disableflags
  _m.opt.gravity = opt__gravity
  _m.opt.impratio = opt__impratio
  _m.opt.is_sparse = opt__is_sparse
  _m.opt.iterations = opt__iterations
  _m.opt.ls_iterations = opt__ls_iterations
  _m.opt.ls_parallel = opt__ls_parallel
  _m.opt.ls_tolerance = opt__ls_tolerance
  _m.opt.solver = opt__solver
  _m.opt.timestep = opt__timestep
  _m.opt.tolerance = opt__tolerance
  _m.opt.viscosity = opt__viscosity
  _m.opt.wind = opt__wind
  _m.qLD_updates = qLD_updates
  _m.qM_fullm_i = qM_fullm_i
  _m.qM_fullm_j = qM_fullm_j
  _m.qM_madr_ij = qM_madr_ij
  _m.qM_mulm_i = qM_mulm_i
  _m.qM_mulm_j = qM_mulm_j
  _m.qM_tiles = qM_tiles
  _m.qpos0 = qpos0
  _m.qpos_spring = qpos_spring
  _m.sensor_acc_adr = sensor_acc_adr
  _m.sensor_adr = sensor_adr
  _m.sensor_cutoff = sensor_cutoff
  _m.sensor_datatype = sensor_datatype
  _m.sensor_objid = sensor_objid
  _m.sensor_objtype = sensor_objtype
  _m.sensor_pos_adr = sensor_pos_adr
  _m.sensor_refid = sensor_refid
  _m.sensor_reftype = sensor_reftype
  _m.sensor_rne_postconstraint = sensor_rne_postconstraint
  _m.sensor_subtree_vel = sensor_subtree_vel
  _m.sensor_type = sensor_type
  _m.sensor_vel_adr = sensor_vel_adr
  _m.site_bodyid = site_bodyid
  _m.site_pos = site_pos
  _m.site_quat = site_quat
  _m.stat.meaninertia = stat__meaninertia
  _m.subtree_mass = subtree_mass
  _m.ten_wrapadr_site = ten_wrapadr_site
  _m.ten_wrapnum_site = ten_wrapnum_site
  _m.tendon_adr = tendon_adr
  _m.tendon_invweight0 = tendon_invweight0
  _m.tendon_jnt_adr = tendon_jnt_adr
  _m.tendon_length0 = tendon_length0
  _m.tendon_limited_adr = tendon_limited_adr
  _m.tendon_margin = tendon_margin
  _m.tendon_num = tendon_num
  _m.tendon_range = tendon_range
  _m.tendon_site_pair_adr = tendon_site_pair_adr
  _m.tendon_solimp_lim = tendon_solimp_lim
  _m.tendon_solref_lim = tendon_solref_lim
  _m.wrap_jnt_adr = wrap_jnt_adr
  _m.wrap_objid = wrap_objid
  _m.wrap_prm = wrap_prm
  _m.wrap_site_adr = wrap_site_adr
  _m.wrap_site_pair_adr = wrap_site_pair_adr
  _m.wrap_type = wrap_type
  _d.act = act
  _d.act_dot = act_dot
  _d.actuator_force = actuator_force
  _d.actuator_length = actuator_length
  _d.actuator_moment = actuator_moment
  _d.actuator_velocity = actuator_velocity
  _d.cacc = cacc
  _d.cam_xmat = cam_xmat
  _d.cam_xpos = cam_xpos
  _d.cdof = cdof
  _d.cdof_dot = cdof_dot
  _d.cfrc_ext = cfrc_ext
  _d.cfrc_int = cfrc_int
  _d.cinert = cinert
  _d.collision_pair = collision_pair
  _d.collision_pairid = collision_pairid
  _d.collision_worldid = collision_worldid
  _d.contact.dim = contact__dim
  _d.contact.dist = contact__dist
  _d.contact.efc_address = contact__efc_address
  _d.contact.frame = contact__frame
  _d.contact.friction = contact__friction
  _d.contact.geom = contact__geom
  _d.contact.includemargin = contact__includemargin
  _d.contact.pos = contact__pos
  _d.contact.solimp = contact__solimp
  _d.contact.solref = contact__solref
  _d.contact.solreffriction = contact__solreffriction
  _d.contact.worldid = contact__worldid
  _d.crb = crb
  _d.ctrl = ctrl
  _d.cvel = cvel
  _d.efc.D = efc__D
  _d.efc.J = efc__J
  _d.efc.Jaref = efc__Jaref
  _d.efc.Ma = efc__Ma
  _d.efc.Mgrad = efc__Mgrad
  _d.efc.active = efc__active
  _d.efc.alpha = efc__alpha
  _d.efc.aref = efc__aref
  _d.efc.beta = efc__beta
  _d.efc.beta_den = efc__beta_den
  _d.efc.beta_num = efc__beta_num
  _d.efc.condim = efc__condim
  _d.efc.cost = efc__cost
  _d.efc.cost_candidate = efc__cost_candidate
  _d.efc.done = efc__done
  _d.efc.force = efc__force
  _d.efc.frictionloss = efc__frictionloss
  _d.efc.gauss = efc__gauss
  _d.efc.grad = efc__grad
  _d.efc.grad_dot = efc__grad_dot
  _d.efc.gtol = efc__gtol
  _d.efc.h = efc__h
  _d.efc.hi = efc__hi
  _d.efc.hi_alpha = efc__hi_alpha
  _d.efc.hi_next = efc__hi_next
  _d.efc.hi_next_alpha = efc__hi_next_alpha
  _d.efc.id = efc__id
  _d.efc.jv = efc__jv
  _d.efc.lo = efc__lo
  _d.efc.lo_alpha = efc__lo_alpha
  _d.efc.lo_next = efc__lo_next
  _d.efc.lo_next_alpha = efc__lo_next_alpha
  _d.efc.ls_done = efc__ls_done
  _d.efc.margin = efc__margin
  _d.efc.mid = efc__mid
  _d.efc.mid_alpha = efc__mid_alpha
  _d.efc.mv = efc__mv
  _d.efc.p0 = efc__p0
  _d.efc.pos = efc__pos
  _d.efc.prev_Mgrad = efc__prev_Mgrad
  _d.efc.prev_cost = efc__prev_cost
  _d.efc.prev_grad = efc__prev_grad
  _d.efc.quad = efc__quad
  _d.efc.quad_gauss = efc__quad_gauss
  _d.efc.quad_total_candidate = efc__quad_total_candidate
  _d.efc.search = efc__search
  _d.efc.search_dot = efc__search_dot
  _d.efc.solver_niter = efc__solver_niter
  _d.efc.u = efc__u
  _d.efc.uu = efc__uu
  _d.efc.uv = efc__uv
  _d.efc.vv = efc__vv
  _d.efc.worldid = efc__worldid
  _d.eq_active = eq_active
  _d.fluid_applied = fluid_applied
  _d.geom_xmat = geom_xmat
  _d.geom_xpos = geom_xpos
  _d.light_xdir = light_xdir
  _d.light_xpos = light_xpos
  _d.mocap_pos = mocap_pos
  _d.mocap_quat = mocap_quat
  _d.ncollision = ncollision
  _d.ncon = ncon
  _d.nconmax = nconmax
  _d.ne = ne
  _d.ne_connect = ne_connect
  _d.ne_jnt = ne_jnt
  _d.ne_ten = ne_ten
  _d.ne_weld = ne_weld
  _d.nefc = nefc
  _d.nf = nf
  _d.njmax = njmax
  _d.nl = nl
  _d.qLD = qLD
  _d.qLDiagInv = qLDiagInv
  _d.qM = qM
  _d.qacc = qacc
  _d.qacc_smooth = qacc_smooth
  _d.qacc_warmstart = qacc_warmstart
  _d.qfrc_actuator = qfrc_actuator
  _d.qfrc_applied = qfrc_applied
  _d.qfrc_bias = qfrc_bias
  _d.qfrc_constraint = qfrc_constraint
  _d.qfrc_damper = qfrc_damper
  _d.qfrc_fluid = qfrc_fluid
  _d.qfrc_gravcomp = qfrc_gravcomp
  _d.qfrc_passive = qfrc_passive
  _d.qfrc_smooth = qfrc_smooth
  _d.qfrc_spring = qfrc_spring
  _d.qpos = qpos
  _d.qvel = qvel
  _d.sap_cumulative_sum = sap_cumulative_sum
  _d.sap_projection_lower = sap_projection_lower
  _d.sap_projection_upper = sap_projection_upper
  _d.sap_range = sap_range
  _d.sap_segment_index = sap_segment_index
  _d.sap_sort_index = sap_sort_index
  _d.sensordata = sensordata
  _d.site_xmat = site_xmat
  _d.site_xpos = site_xpos
  _d.subtree_angmom = subtree_angmom
  _d.subtree_bodyvel = subtree_bodyvel
  _d.subtree_com = subtree_com
  _d.subtree_linvel = subtree_linvel
  _d.ten_J = ten_J
  _d.ten_length = ten_length
  _d.ten_velocity = ten_velocity
  _d.ten_wrapadr = ten_wrapadr
  _d.ten_wrapnum = ten_wrapnum
  _d.time = time
  _d.wrap_obj = wrap_obj
  _d.wrap_xpos = wrap_xpos
  _d.xanchor = xanchor
  _d.xaxis = xaxis
  _d.xfrc_applied = xfrc_applied
  _d.ximat = ximat
  _d.xipos = xipos
  _d.xmat = xmat
  _d.xpos = xpos
  _d.xquat = xquat
  _d.nworld = _d.qpos.shape[0]
  mjwarp.forward(_m, _d)


def _forward_shim(
    nv: int,
    nu: int,
    na: int,
    nbody: int,
    njnt: int,
    ngeom: int,
    nsite: int,
    ncam: int,
    nlight: int,
    neq: int,
    nmocap: int,
    ngravcomp: int,
    nM: int,
    ntendon: int,
    nlsp: int,
    opt__timestep: float,
    opt__impratio: float,
    opt__tolerance: float,
    opt__ls_tolerance: float,
    opt__gravity: wp.vec3,
    opt__cone: int,
    opt__solver: int,
    opt__iterations: int,
    opt__ls_iterations: int,
    opt__disableflags: int,
    opt__is_sparse: bool,
    opt__ls_parallel: bool,
    opt__wind: wp.vec3,
    opt__density: float,
    opt__viscosity: float,
    stat__meaninertia: float,
    qpos0: wp.array(dtype=float),
    qpos_spring: wp.array(dtype=float),
    qM_fullm_i: wp.array(dtype=int),
    qM_fullm_j: wp.array(dtype=int),
    qM_mulm_i: wp.array(dtype=int),
    qM_mulm_j: wp.array(dtype=int),
    qM_madr_ij: wp.array(dtype=int),
    qLD_updates: tuple[wp.array(dtype=wp.vec3i), ...],
    M_rownnz: wp.array(dtype=int),
    M_rowadr: wp.array(dtype=int),
    mapM2M: wp.array(dtype=int),
    qM_tiles: tuple[mjwarp_types.TileSet, ...],
    body_tree: tuple[wp.array(dtype=int), ...],
    body_parentid: wp.array(dtype=int),
    body_rootid: wp.array(dtype=int),
    body_jntnum: wp.array(dtype=int),
    body_jntadr: wp.array(dtype=int),
    body_dofnum: wp.array(dtype=int),
    body_dofadr: wp.array(dtype=int),
    body_pos: wp.array(dtype=wp.vec3),
    body_quat: wp.array(dtype=wp.quat),
    body_ipos: wp.array(dtype=wp.vec3),
    body_iquat: wp.array(dtype=wp.quat),
    body_mass: wp.array(dtype=float),
    body_subtreemass: wp.array(dtype=float),
    subtree_mass: wp.array(dtype=float),
    body_inertia: wp.array(dtype=wp.vec3),
    body_invweight0: wp.array2d(dtype=float),
    body_gravcomp: wp.array(dtype=float),
    jnt_type: wp.array(dtype=int),
    jnt_qposadr: wp.array(dtype=int),
    jnt_dofadr: wp.array(dtype=int),
    jnt_bodyid: wp.array(dtype=int),
    jnt_actfrclimited: wp.array(dtype=bool),
    jnt_solref: wp.array(dtype=wp.vec2),
    jnt_solimp: wp.array(dtype=mjwarp_types.vec5),
    jnt_pos: wp.array(dtype=wp.vec3),
    jnt_axis: wp.array(dtype=wp.vec3),
    jnt_stiffness: wp.array(dtype=float),
    jnt_range: wp.array2d(dtype=float),
    jnt_actfrcrange: wp.array(dtype=wp.vec2),
    jnt_margin: wp.array(dtype=float),
    jnt_limited_slide_hinge_adr: wp.array(dtype=int),
    jnt_limited_ball_adr: wp.array(dtype=int),
    jnt_actgravcomp: wp.array(dtype=int),
    dof_bodyid: wp.array(dtype=int),
    dof_jntid: wp.array(dtype=int),
    dof_parentid: wp.array(dtype=int),
    dof_Madr: wp.array(dtype=int),
    dof_armature: wp.array(dtype=float),
    dof_damping: wp.array(dtype=float),
    dof_invweight0: wp.array(dtype=float),
    dof_frictionloss: wp.array(dtype=float),
    dof_solimp: wp.array(dtype=mjwarp_types.vec5),
    dof_solref: wp.array(dtype=wp.vec2),
    dof_tri_row: wp.array(dtype=int),
    dof_tri_col: wp.array(dtype=int),
    geom_type: wp.array(dtype=int),
    geom_bodyid: wp.array(dtype=int),
    geom_rbound: wp.array(dtype=float),
    geom_pos: wp.array(dtype=wp.vec3),
    geom_quat: wp.array(dtype=wp.quat),
    geom_margin: wp.array(dtype=float),
    site_bodyid: wp.array(dtype=int),
    site_pos: wp.array(dtype=wp.vec3),
    site_quat: wp.array(dtype=wp.quat),
    cam_mode: wp.array(dtype=int),
    cam_bodyid: wp.array(dtype=int),
    cam_targetbodyid: wp.array(dtype=int),
    cam_pos: wp.array(dtype=wp.vec3),
    cam_quat: wp.array(dtype=wp.quat),
    cam_poscom0: wp.array(dtype=wp.vec3),
    cam_pos0: wp.array(dtype=wp.vec3),
    cam_mat0: wp.array(dtype=wp.mat33),
    cam_fovy: wp.array(dtype=float),
    cam_resolution: wp.array(dtype=wp.vec2i),
    cam_sensorsize: wp.array(dtype=wp.vec2),
    cam_intrinsic: wp.array(dtype=wp.vec4),
    light_mode: wp.array(dtype=int),
    light_bodyid: wp.array(dtype=int),
    light_targetbodyid: wp.array(dtype=int),
    light_pos: wp.array(dtype=wp.vec3),
    light_dir: wp.array(dtype=wp.vec3),
    light_poscom0: wp.array(dtype=wp.vec3),
    light_pos0: wp.array(dtype=wp.vec3),
    light_dir0: wp.array(dtype=wp.vec3),
    eq_obj1id: wp.array(dtype=int),
    eq_obj2id: wp.array(dtype=int),
    eq_objtype: wp.array(dtype=int),
    eq_solref: wp.array(dtype=wp.vec2),
    eq_solimp: wp.array(dtype=mjwarp_types.vec5),
    eq_data: wp.array(dtype=mjwarp_types.vec11),
    eq_connect_adr: wp.array(dtype=int),
    eq_wld_adr: wp.array(dtype=int),
    eq_jnt_adr: wp.array(dtype=int),
    eq_ten_adr: wp.array(dtype=int),
    actuator_moment_tiles_nv: tuple[mjwarp_types.TileSet, ...],
    actuator_moment_tiles_nu: tuple[mjwarp_types.TileSet, ...],
    actuator_trntype: wp.array(dtype=int),
    actuator_dyntype: wp.array(dtype=int),
    actuator_gaintype: wp.array(dtype=int),
    actuator_biastype: wp.array(dtype=int),
    actuator_trnid: wp.array(dtype=wp.vec2i),
    actuator_actadr: wp.array(dtype=int),
    actuator_actnum: wp.array(dtype=int),
    actuator_ctrllimited: wp.array(dtype=bool),
    actuator_forcelimited: wp.array(dtype=bool),
    actuator_dynprm: wp.array(dtype=mjwarp_types.vec10f),
    actuator_gainprm: wp.array(dtype=mjwarp_types.vec10f),
    actuator_biasprm: wp.array(dtype=mjwarp_types.vec10f),
    actuator_ctrlrange: wp.array(dtype=wp.vec2),
    actuator_forcerange: wp.array(dtype=wp.vec2),
    actuator_gear: wp.array(dtype=wp.spatial_vector),
    nxn_geom_pair: wp.array(dtype=wp.vec2i),
    nxn_pairid: wp.array(dtype=int),
    condim_max: int,
    tendon_adr: wp.array(dtype=int),
    tendon_num: wp.array(dtype=int),
    tendon_limited_adr: wp.array(dtype=int),
    tendon_solref_lim: wp.array(dtype=wp.vec2),
    tendon_solimp_lim: wp.array(dtype=mjwarp_types.vec5),
    tendon_range: wp.array(dtype=wp.vec2),
    tendon_margin: wp.array(dtype=float),
    tendon_length0: wp.array(dtype=float),
    tendon_invweight0: wp.array(dtype=float),
    wrap_objid: wp.array(dtype=int),
    wrap_prm: wp.array(dtype=float),
    wrap_type: wp.array(dtype=int),
    tendon_jnt_adr: wp.array(dtype=int),
    tendon_site_pair_adr: wp.array(dtype=int),
    ten_wrapadr_site: wp.array(dtype=int),
    ten_wrapnum_site: wp.array(dtype=int),
    wrap_jnt_adr: wp.array(dtype=int),
    wrap_site_adr: wp.array(dtype=int),
    wrap_site_pair_adr: wp.array(dtype=int),
    sensor_type: wp.array(dtype=int),
    sensor_datatype: wp.array(dtype=int),
    sensor_objtype: wp.array(dtype=int),
    sensor_objid: wp.array(dtype=int),
    sensor_reftype: wp.array(dtype=int),
    sensor_refid: wp.array(dtype=int),
    sensor_adr: wp.array(dtype=int),
    sensor_cutoff: wp.array(dtype=float),
    sensor_pos_adr: wp.array(dtype=int),
    sensor_vel_adr: wp.array(dtype=int),
    sensor_acc_adr: wp.array(dtype=int),
    sensor_subtree_vel: bool,
    sensor_rne_postconstraint: bool,
    mocap_bodyid: wp.array(dtype=int),
    nconmax: int,
    njmax: int,
    ncon: wp.array(dtype=int),
    time: wp.array(dtype=float),
    qpos: wp.array(dtype=float),
    qvel: wp.array(dtype=float),
    act: wp.array(dtype=float),
    qacc_warmstart: wp.array(dtype=float),
    ctrl: wp.array(dtype=float),
    qfrc_applied: wp.array(dtype=float),
    xfrc_applied: wp.array(dtype=wp.spatial_vector),
    eq_active: wp.array(dtype=bool),
    mocap_pos: wp.array(dtype=wp.vec3),
    mocap_quat: wp.array(dtype=wp.quat),
    qLD: wp.array2d(dtype=float),
    qLDiagInv: wp.array(dtype=float),
    qfrc_fluid: wp.array(dtype=float),
    qacc_smooth: wp.array(dtype=float),
    contact__dist: wp.array(dtype=float),
    contact__pos: wp.array(dtype=wp.vec3),
    contact__frame: wp.array(dtype=wp.mat33),
    contact__includemargin: wp.array(dtype=float),
    contact__friction: wp.array(dtype=mjwarp_types.vec5),
    contact__solref: wp.array(dtype=wp.vec2),
    contact__solreffriction: wp.array(dtype=wp.vec2),
    contact__solimp: wp.array(dtype=mjwarp_types.vec5),
    contact__dim: wp.array(dtype=int),
    contact__geom: wp.array(dtype=wp.vec2i),
    contact__worldid: wp.array(dtype=int),
    efc__mv: wp.array(dtype=float),
    sap_cumulative_sum: wp.array(dtype=int),
    sap_segment_index: wp.array(dtype=int),
    ne: wp.array(dtype=int),
    ne_connect: wp.array(dtype=int),
    ne_weld: wp.array(dtype=int),
    ne_jnt: wp.array(dtype=int),
    ne_ten: wp.array(dtype=int),
    nf: wp.array(dtype=int),
    nl: wp.array(dtype=int),
    nefc: wp.array(dtype=int),
    fluid_applied: wp.array(dtype=wp.spatial_vector),
    qacc: wp.array(dtype=float),
    act_dot: wp.array(dtype=float),
    xpos: wp.array(dtype=wp.vec3),
    xquat: wp.array(dtype=wp.quat),
    xmat: wp.array(dtype=wp.mat33),
    xipos: wp.array(dtype=wp.vec3),
    ximat: wp.array(dtype=wp.mat33),
    xanchor: wp.array(dtype=wp.vec3),
    xaxis: wp.array(dtype=wp.vec3),
    geom_xpos: wp.array(dtype=wp.vec3),
    geom_xmat: wp.array(dtype=wp.mat33),
    site_xpos: wp.array(dtype=wp.vec3),
    site_xmat: wp.array(dtype=wp.mat33),
    cam_xpos: wp.array(dtype=wp.vec3),
    cam_xmat: wp.array(dtype=wp.mat33),
    light_xpos: wp.array(dtype=wp.vec3),
    light_xdir: wp.array(dtype=wp.vec3),
    subtree_com: wp.array(dtype=wp.vec3),
    cdof: wp.array(dtype=wp.spatial_vector),
    cinert: wp.array(dtype=mjwarp_types.vec10),
    actuator_length: wp.array(dtype=float),
    actuator_moment: wp.array2d(dtype=float),
    crb: wp.array(dtype=mjwarp_types.vec10),
    qM: wp.array2d(dtype=float),
    ten_velocity: wp.array(dtype=float),
    actuator_velocity: wp.array(dtype=float),
    cvel: wp.array(dtype=wp.spatial_vector),
    cdof_dot: wp.array(dtype=wp.spatial_vector),
    qfrc_bias: wp.array(dtype=float),
    qfrc_spring: wp.array(dtype=float),
    qfrc_damper: wp.array(dtype=float),
    qfrc_gravcomp: wp.array(dtype=float),
    qfrc_passive: wp.array(dtype=float),
    subtree_linvel: wp.array(dtype=wp.vec3),
    subtree_angmom: wp.array(dtype=wp.vec3),
    subtree_bodyvel: wp.array(dtype=wp.spatial_vector),
    actuator_force: wp.array(dtype=float),
    qfrc_actuator: wp.array(dtype=float),
    qfrc_smooth: wp.array(dtype=float),
    qfrc_constraint: wp.array(dtype=float),
    contact__efc_address: wp.array(dtype=int),
    efc__worldid: wp.array(dtype=int),
    efc__id: wp.array(dtype=int),
    efc__J: wp.array(dtype=float),
    efc__pos: wp.array(dtype=float),
    efc__margin: wp.array(dtype=float),
    efc__D: wp.array(dtype=float),
    efc__aref: wp.array(dtype=float),
    efc__frictionloss: wp.array(dtype=float),
    efc__force: wp.array(dtype=float),
    efc__Jaref: wp.array(dtype=float),
    efc__Ma: wp.array(dtype=float),
    efc__grad: wp.array(dtype=float),
    efc__grad_dot: wp.array(dtype=float),
    efc__Mgrad: wp.array(dtype=float),
    efc__search: wp.array(dtype=float),
    efc__search_dot: wp.array(dtype=float),
    efc__gauss: wp.array(dtype=float),
    efc__cost: wp.array(dtype=float),
    efc__prev_cost: wp.array(dtype=float),
    efc__solver_niter: wp.array(dtype=int),
    efc__active: wp.array(dtype=bool),
    efc__gtol: wp.array(dtype=float),
    efc__jv: wp.array(dtype=float),
    efc__quad: wp.array(dtype=wp.vec3),
    efc__quad_gauss: wp.array(dtype=wp.vec3),
    efc__h: wp.array(dtype=float),
    efc__alpha: wp.array(dtype=float),
    efc__prev_grad: wp.array(dtype=float),
    efc__prev_Mgrad: wp.array(dtype=float),
    efc__beta: wp.array(dtype=float),
    efc__beta_num: wp.array(dtype=float),
    efc__beta_den: wp.array(dtype=float),
    efc__done: wp.array(dtype=bool),
    efc__ls_done: wp.array(dtype=bool),
    efc__p0: wp.array(dtype=wp.vec3),
    efc__lo: wp.array(dtype=wp.vec3),
    efc__lo_alpha: wp.array(dtype=float),
    efc__hi: wp.array(dtype=wp.vec3),
    efc__hi_alpha: wp.array(dtype=float),
    efc__lo_next: wp.array(dtype=wp.vec3),
    efc__lo_next_alpha: wp.array(dtype=float),
    efc__hi_next: wp.array(dtype=wp.vec3),
    efc__hi_next_alpha: wp.array(dtype=float),
    efc__mid: wp.array(dtype=wp.vec3),
    efc__mid_alpha: wp.array(dtype=float),
    efc__cost_candidate: wp.array(dtype=float),
    efc__quad_total_candidate: wp.array(dtype=wp.vec3),
    efc__u: wp.array(dtype=mjwarp_types.vec6),
    efc__uu: wp.array(dtype=float),
    efc__uv: wp.array(dtype=float),
    efc__vv: wp.array(dtype=float),
    efc__condim: wp.array(dtype=int),
    sap_projection_lower: wp.array(dtype=float),
    sap_projection_upper: wp.array(dtype=float),
    sap_sort_index: wp.array(dtype=int),
    sap_range: wp.array(dtype=int),
    collision_pair: wp.array(dtype=wp.vec2i),
    collision_pairid: wp.array(dtype=int),
    collision_worldid: wp.array(dtype=int),
    ncollision: wp.array(dtype=int),
    cacc: wp.array(dtype=wp.spatial_vector),
    cfrc_int: wp.array(dtype=wp.spatial_vector),
    cfrc_ext: wp.array(dtype=wp.spatial_vector),
    ten_length: wp.array(dtype=float),
    ten_J: wp.array(dtype=float),
    ten_wrapadr: wp.array(dtype=int),
    ten_wrapnum: wp.array(dtype=int),
    wrap_obj: wp.array(dtype=wp.vec2i),
    wrap_xpos: wp.array(dtype=wp.spatial_vector),
    sensordata: wp.array(dtype=float),
):
  args = (
      nv,
      nu,
      na,
      nbody,
      njnt,
      ngeom,
      nsite,
      ncam,
      nlight,
      neq,
      nmocap,
      ngravcomp,
      nM,
      ntendon,
      nlsp,
      opt__timestep,
      opt__impratio,
      opt__tolerance,
      opt__ls_tolerance,
      opt__gravity,
      opt__cone,
      opt__solver,
      opt__iterations,
      opt__ls_iterations,
      opt__disableflags,
      opt__is_sparse,
      opt__ls_parallel,
      opt__wind,
      opt__density,
      opt__viscosity,
      stat__meaninertia,
      qpos0,
      qpos_spring,
      qM_fullm_i,
      qM_fullm_j,
      qM_mulm_i,
      qM_mulm_j,
      qM_madr_ij,
      qLD_updates,
      M_rownnz,
      M_rowadr,
      mapM2M,
      qM_tiles,
      body_tree,
      body_parentid,
      body_rootid,
      body_jntnum,
      body_jntadr,
      body_dofnum,
      body_dofadr,
      body_pos,
      body_quat,
      body_ipos,
      body_iquat,
      body_mass,
      body_subtreemass,
      subtree_mass,
      body_inertia,
      body_invweight0,
      body_gravcomp,
      jnt_type,
      jnt_qposadr,
      jnt_dofadr,
      jnt_bodyid,
      jnt_actfrclimited,
      jnt_solref,
      jnt_solimp,
      jnt_pos,
      jnt_axis,
      jnt_stiffness,
      jnt_range,
      jnt_actfrcrange,
      jnt_margin,
      jnt_limited_slide_hinge_adr,
      jnt_limited_ball_adr,
      jnt_actgravcomp,
      dof_bodyid,
      dof_jntid,
      dof_parentid,
      dof_Madr,
      dof_armature,
      dof_damping,
      dof_invweight0,
      dof_frictionloss,
      dof_solimp,
      dof_solref,
      dof_tri_row,
      dof_tri_col,
      geom_type,
      geom_bodyid,
      geom_rbound,
      geom_pos,
      geom_quat,
      geom_margin,
      site_bodyid,
      site_pos,
      site_quat,
      cam_mode,
      cam_bodyid,
      cam_targetbodyid,
      cam_pos,
      cam_quat,
      cam_poscom0,
      cam_pos0,
      cam_mat0,
      cam_fovy,
      cam_resolution,
      cam_sensorsize,
      cam_intrinsic,
      light_mode,
      light_bodyid,
      light_targetbodyid,
      light_pos,
      light_dir,
      light_poscom0,
      light_pos0,
      light_dir0,
      eq_obj1id,
      eq_obj2id,
      eq_objtype,
      eq_solref,
      eq_solimp,
      eq_data,
      eq_connect_adr,
      eq_wld_adr,
      eq_jnt_adr,
      eq_ten_adr,
      actuator_moment_tiles_nv,
      actuator_moment_tiles_nu,
      actuator_trntype,
      actuator_dyntype,
      actuator_gaintype,
      actuator_biastype,
      actuator_trnid,
      actuator_actadr,
      actuator_actnum,
      actuator_ctrllimited,
      actuator_forcelimited,
      actuator_dynprm,
      actuator_gainprm,
      actuator_biasprm,
      actuator_ctrlrange,
      actuator_forcerange,
      actuator_gear,
      nxn_geom_pair,
      nxn_pairid,
      condim_max,
      tendon_adr,
      tendon_num,
      tendon_limited_adr,
      tendon_solref_lim,
      tendon_solimp_lim,
      tendon_range,
      tendon_margin,
      tendon_length0,
      tendon_invweight0,
      wrap_objid,
      wrap_prm,
      wrap_type,
      tendon_jnt_adr,
      tendon_site_pair_adr,
      ten_wrapadr_site,
      ten_wrapnum_site,
      wrap_jnt_adr,
      wrap_site_adr,
      wrap_site_pair_adr,
      sensor_type,
      sensor_datatype,
      sensor_objtype,
      sensor_objid,
      sensor_reftype,
      sensor_refid,
      sensor_adr,
      sensor_cutoff,
      sensor_pos_adr,
      sensor_vel_adr,
      sensor_acc_adr,
      sensor_subtree_vel,
      sensor_rne_postconstraint,
      mocap_bodyid,
      nconmax,
      njmax,
      ncon,
      time,
      qpos,
      qvel,
      act,
      qacc_warmstart,
      ctrl,
      qfrc_applied,
      xfrc_applied,
      eq_active,
      mocap_pos,
      mocap_quat,
      qLD,
      qLDiagInv,
      qfrc_fluid,
      qacc_smooth,
      contact__dist,
      contact__pos,
      contact__frame,
      contact__includemargin,
      contact__friction,
      contact__solref,
      contact__solreffriction,
      contact__solimp,
      contact__dim,
      contact__geom,
      contact__worldid,
      efc__mv,
      sap_cumulative_sum,
      sap_segment_index,
      ne,
      ne_connect,
      ne_weld,
      ne_jnt,
      ne_ten,
      nf,
      nl,
      nefc,
      fluid_applied,
      qacc,
      act_dot,
      xpos,
      xquat,
      xmat,
      xipos,
      ximat,
      xanchor,
      xaxis,
      geom_xpos,
      geom_xmat,
      site_xpos,
      site_xmat,
      cam_xpos,
      cam_xmat,
      light_xpos,
      light_xdir,
      subtree_com,
      cdof,
      cinert,
      actuator_length,
      actuator_moment,
      crb,
      qM,
      ten_velocity,
      actuator_velocity,
      cvel,
      cdof_dot,
      qfrc_bias,
      qfrc_spring,
      qfrc_damper,
      qfrc_gravcomp,
      qfrc_passive,
      subtree_linvel,
      subtree_angmom,
      subtree_bodyvel,
      actuator_force,
      qfrc_actuator,
      qfrc_smooth,
      qfrc_constraint,
      contact__efc_address,
      efc__worldid,
      efc__id,
      efc__J,
      efc__pos,
      efc__margin,
      efc__D,
      efc__aref,
      efc__frictionloss,
      efc__force,
      efc__Jaref,
      efc__Ma,
      efc__grad,
      efc__grad_dot,
      efc__Mgrad,
      efc__search,
      efc__search_dot,
      efc__gauss,
      efc__cost,
      efc__prev_cost,
      efc__solver_niter,
      efc__active,
      efc__gtol,
      efc__jv,
      efc__quad,
      efc__quad_gauss,
      efc__h,
      efc__alpha,
      efc__prev_grad,
      efc__prev_Mgrad,
      efc__beta,
      efc__beta_num,
      efc__beta_den,
      efc__done,
      efc__ls_done,
      efc__p0,
      efc__lo,
      efc__lo_alpha,
      efc__hi,
      efc__hi_alpha,
      efc__lo_next,
      efc__lo_next_alpha,
      efc__hi_next,
      efc__hi_next_alpha,
      efc__mid,
      efc__mid_alpha,
      efc__cost_candidate,
      efc__quad_total_candidate,
      efc__u,
      efc__uu,
      efc__uv,
      efc__vv,
      efc__condim,
      sap_projection_lower,
      sap_projection_upper,
      sap_sort_index,
      sap_range,
      collision_pair,
      collision_pairid,
      collision_worldid,
      ncollision,
      cacc,
      cfrc_int,
      cfrc_ext,
      ten_length,
      ten_J,
      ten_wrapadr,
      ten_wrapnum,
      wrap_obj,
      wrap_xpos,
      sensordata,
  )
  names = (
      "nv",
      "nu",
      "na",
      "nbody",
      "njnt",
      "ngeom",
      "nsite",
      "ncam",
      "nlight",
      "neq",
      "nmocap",
      "ngravcomp",
      "nM",
      "ntendon",
      "nlsp",
      "opt__timestep",
      "opt__impratio",
      "opt__tolerance",
      "opt__ls_tolerance",
      "opt__gravity",
      "opt__cone",
      "opt__solver",
      "opt__iterations",
      "opt__ls_iterations",
      "opt__disableflags",
      "opt__is_sparse",
      "opt__ls_parallel",
      "opt__wind",
      "opt__density",
      "opt__viscosity",
      "stat__meaninertia",
      "qpos0",
      "qpos_spring",
      "qM_fullm_i",
      "qM_fullm_j",
      "qM_mulm_i",
      "qM_mulm_j",
      "qM_madr_ij",
      "qLD_updates",
      "M_rownnz",
      "M_rowadr",
      "mapM2M",
      "qM_tiles",
      "body_tree",
      "body_parentid",
      "body_rootid",
      "body_jntnum",
      "body_jntadr",
      "body_dofnum",
      "body_dofadr",
      "body_pos",
      "body_quat",
      "body_ipos",
      "body_iquat",
      "body_mass",
      "body_subtreemass",
      "subtree_mass",
      "body_inertia",
      "body_invweight0",
      "body_gravcomp",
      "jnt_type",
      "jnt_qposadr",
      "jnt_dofadr",
      "jnt_bodyid",
      "jnt_actfrclimited",
      "jnt_solref",
      "jnt_solimp",
      "jnt_pos",
      "jnt_axis",
      "jnt_stiffness",
      "jnt_range",
      "jnt_actfrcrange",
      "jnt_margin",
      "jnt_limited_slide_hinge_adr",
      "jnt_limited_ball_adr",
      "jnt_actgravcomp",
      "dof_bodyid",
      "dof_jntid",
      "dof_parentid",
      "dof_Madr",
      "dof_armature",
      "dof_damping",
      "dof_invweight0",
      "dof_frictionloss",
      "dof_solimp",
      "dof_solref",
      "dof_tri_row",
      "dof_tri_col",
      "geom_type",
      "geom_bodyid",
      "geom_rbound",
      "geom_pos",
      "geom_quat",
      "geom_margin",
      "site_bodyid",
      "site_pos",
      "site_quat",
      "cam_mode",
      "cam_bodyid",
      "cam_targetbodyid",
      "cam_pos",
      "cam_quat",
      "cam_poscom0",
      "cam_pos0",
      "cam_mat0",
      "cam_fovy",
      "cam_resolution",
      "cam_sensorsize",
      "cam_intrinsic",
      "light_mode",
      "light_bodyid",
      "light_targetbodyid",
      "light_pos",
      "light_dir",
      "light_poscom0",
      "light_pos0",
      "light_dir0",
      "eq_obj1id",
      "eq_obj2id",
      "eq_objtype",
      "eq_solref",
      "eq_solimp",
      "eq_data",
      "eq_connect_adr",
      "eq_wld_adr",
      "eq_jnt_adr",
      "eq_ten_adr",
      "actuator_moment_tiles_nv",
      "actuator_moment_tiles_nu",
      "actuator_trntype",
      "actuator_dyntype",
      "actuator_gaintype",
      "actuator_biastype",
      "actuator_trnid",
      "actuator_actadr",
      "actuator_actnum",
      "actuator_ctrllimited",
      "actuator_forcelimited",
      "actuator_dynprm",
      "actuator_gainprm",
      "actuator_biasprm",
      "actuator_ctrlrange",
      "actuator_forcerange",
      "actuator_gear",
      "nxn_geom_pair",
      "nxn_pairid",
      "condim_max",
      "tendon_adr",
      "tendon_num",
      "tendon_limited_adr",
      "tendon_solref_lim",
      "tendon_solimp_lim",
      "tendon_range",
      "tendon_margin",
      "tendon_length0",
      "tendon_invweight0",
      "wrap_objid",
      "wrap_prm",
      "wrap_type",
      "tendon_jnt_adr",
      "tendon_site_pair_adr",
      "ten_wrapadr_site",
      "ten_wrapnum_site",
      "wrap_jnt_adr",
      "wrap_site_adr",
      "wrap_site_pair_adr",
      "sensor_type",
      "sensor_datatype",
      "sensor_objtype",
      "sensor_objid",
      "sensor_reftype",
      "sensor_refid",
      "sensor_adr",
      "sensor_cutoff",
      "sensor_pos_adr",
      "sensor_vel_adr",
      "sensor_acc_adr",
      "sensor_subtree_vel",
      "sensor_rne_postconstraint",
      "mocap_bodyid",
      "nconmax",
      "njmax",
      "ncon",
      "time",
      "qpos",
      "qvel",
      "act",
      "qacc_warmstart",
      "ctrl",
      "qfrc_applied",
      "xfrc_applied",
      "eq_active",
      "mocap_pos",
      "mocap_quat",
      "qLD",
      "qLDiagInv",
      "qfrc_fluid",
      "qacc_smooth",
      "contact__dist",
      "contact__pos",
      "contact__frame",
      "contact__includemargin",
      "contact__friction",
      "contact__solref",
      "contact__solreffriction",
      "contact__solimp",
      "contact__dim",
      "contact__geom",
      "contact__worldid",
      "efc__mv",
      "sap_cumulative_sum",
      "sap_segment_index",
      "ne",
      "ne_connect",
      "ne_weld",
      "ne_jnt",
      "ne_ten",
      "nf",
      "nl",
      "nefc",
      "fluid_applied",
      "qacc",
      "act_dot",
      "xpos",
      "xquat",
      "xmat",
      "xipos",
      "ximat",
      "xanchor",
      "xaxis",
      "geom_xpos",
      "geom_xmat",
      "site_xpos",
      "site_xmat",
      "cam_xpos",
      "cam_xmat",
      "light_xpos",
      "light_xdir",
      "subtree_com",
      "cdof",
      "cinert",
      "actuator_length",
      "actuator_moment",
      "crb",
      "qM",
      "ten_velocity",
      "actuator_velocity",
      "cvel",
      "cdof_dot",
      "qfrc_bias",
      "qfrc_spring",
      "qfrc_damper",
      "qfrc_gravcomp",
      "qfrc_passive",
      "subtree_linvel",
      "subtree_angmom",
      "subtree_bodyvel",
      "actuator_force",
      "qfrc_actuator",
      "qfrc_smooth",
      "qfrc_constraint",
      "contact__efc_address",
      "efc__worldid",
      "efc__id",
      "efc__J",
      "efc__pos",
      "efc__margin",
      "efc__D",
      "efc__aref",
      "efc__frictionloss",
      "efc__force",
      "efc__Jaref",
      "efc__Ma",
      "efc__grad",
      "efc__grad_dot",
      "efc__Mgrad",
      "efc__search",
      "efc__search_dot",
      "efc__gauss",
      "efc__cost",
      "efc__prev_cost",
      "efc__solver_niter",
      "efc__active",
      "efc__gtol",
      "efc__jv",
      "efc__quad",
      "efc__quad_gauss",
      "efc__h",
      "efc__alpha",
      "efc__prev_grad",
      "efc__prev_Mgrad",
      "efc__beta",
      "efc__beta_num",
      "efc__beta_den",
      "efc__done",
      "efc__ls_done",
      "efc__p0",
      "efc__lo",
      "efc__lo_alpha",
      "efc__hi",
      "efc__hi_alpha",
      "efc__lo_next",
      "efc__lo_next_alpha",
      "efc__hi_next",
      "efc__hi_next_alpha",
      "efc__mid",
      "efc__mid_alpha",
      "efc__cost_candidate",
      "efc__quad_total_candidate",
      "efc__u",
      "efc__uu",
      "efc__uv",
      "efc__vv",
      "efc__condim",
      "sap_projection_lower",
      "sap_projection_upper",
      "sap_sort_index",
      "sap_range",
      "collision_pair",
      "collision_pairid",
      "collision_worldid",
      "ncollision",
      "cacc",
      "cfrc_int",
      "cfrc_ext",
      "ten_length",
      "ten_J",
      "ten_wrapadr",
      "ten_wrapnum",
      "wrap_obj",
      "wrap_xpos",
      "sensordata",
  )
  args = ffi_helper.format_args_for_warp(*args, names=names, kernel=_forward)
  _forward(*args)


def forward(m: types.Model, d: types.Data):
  output_dims = {
      "ne": d._impl.ne.shape,
      "ne_connect": d._impl.ne_connect.shape,
      "ne_weld": d._impl.ne_weld.shape,
      "ne_jnt": d._impl.ne_jnt.shape,
      "ne_ten": d._impl.ne_ten.shape,
      "nf": d._impl.nf.shape,
      "nl": d._impl.nl.shape,
      "nefc": d._impl.nefc.shape,
      "fluid_applied": d._impl.fluid_applied.shape,
      "qacc": d.qacc.shape,
      "act_dot": d.act_dot.shape,
      "xpos": d.xpos.shape,
      "xquat": d.xquat.shape,
      "xmat": d.xmat.shape,
      "xipos": d.xipos.shape,
      "ximat": d.ximat.shape,
      "xanchor": d.xanchor.shape,
      "xaxis": d.xaxis.shape,
      "geom_xpos": d.geom_xpos.shape,
      "geom_xmat": d.geom_xmat.shape,
      "site_xpos": d.site_xpos.shape,
      "site_xmat": d.site_xmat.shape,
      "cam_xpos": d.cam_xpos.shape,
      "cam_xmat": d.cam_xmat.shape,
      "light_xpos": d._impl.light_xpos.shape,
      "light_xdir": d._impl.light_xdir.shape,
      "subtree_com": d.subtree_com.shape,
      "cdof": d._impl.cdof.shape,
      "cinert": d._impl.cinert.shape,
      "actuator_length": d._impl.actuator_length.shape,
      "actuator_moment": d._impl.actuator_moment.shape,
      "crb": d._impl.crb.shape,
      "qM": d._impl.qM.shape,
      "ten_velocity": d._impl.ten_velocity.shape,
      "actuator_velocity": d._impl.actuator_velocity.shape,
      "cvel": d.cvel.shape,
      "cdof_dot": d._impl.cdof_dot.shape,
      "qfrc_bias": d.qfrc_bias.shape,
      "qfrc_spring": d._impl.qfrc_spring.shape,
      "qfrc_damper": d._impl.qfrc_damper.shape,
      "qfrc_gravcomp": d.qfrc_gravcomp.shape,
      "qfrc_passive": d.qfrc_passive.shape,
      "subtree_linvel": d._impl.subtree_linvel.shape,
      "subtree_angmom": d._impl.subtree_angmom.shape,
      "subtree_bodyvel": d._impl.subtree_bodyvel.shape,
      "actuator_force": d.actuator_force.shape,
      "qfrc_actuator": d.qfrc_actuator.shape,
      "qfrc_smooth": d.qfrc_smooth.shape,
      "qfrc_constraint": d.qfrc_constraint.shape,
      "contact__efc_address": d._impl.contact__efc_address.shape,
      "efc__worldid": d._impl.efc__worldid.shape,
      "efc__id": d._impl.efc__id.shape,
      "efc__J": d._impl.efc__J.shape,
      "efc__pos": d._impl.efc__pos.shape,
      "efc__margin": d._impl.efc__margin.shape,
      "efc__D": d._impl.efc__D.shape,
      "efc__aref": d._impl.efc__aref.shape,
      "efc__frictionloss": d._impl.efc__frictionloss.shape,
      "efc__force": d._impl.efc__force.shape,
      "efc__Jaref": d._impl.efc__Jaref.shape,
      "efc__Ma": d._impl.efc__Ma.shape,
      "efc__grad": d._impl.efc__grad.shape,
      "efc__grad_dot": d._impl.efc__grad_dot.shape,
      "efc__Mgrad": d._impl.efc__Mgrad.shape,
      "efc__search": d._impl.efc__search.shape,
      "efc__search_dot": d._impl.efc__search_dot.shape,
      "efc__gauss": d._impl.efc__gauss.shape,
      "efc__cost": d._impl.efc__cost.shape,
      "efc__prev_cost": d._impl.efc__prev_cost.shape,
      "efc__solver_niter": d._impl.efc__solver_niter.shape,
      "efc__active": d._impl.efc__active.shape,
      "efc__gtol": d._impl.efc__gtol.shape,
      "efc__jv": d._impl.efc__jv.shape,
      "efc__quad": d._impl.efc__quad.shape,
      "efc__quad_gauss": d._impl.efc__quad_gauss.shape,
      "efc__h": d._impl.efc__h.shape,
      "efc__alpha": d._impl.efc__alpha.shape,
      "efc__prev_grad": d._impl.efc__prev_grad.shape,
      "efc__prev_Mgrad": d._impl.efc__prev_Mgrad.shape,
      "efc__beta": d._impl.efc__beta.shape,
      "efc__beta_num": d._impl.efc__beta_num.shape,
      "efc__beta_den": d._impl.efc__beta_den.shape,
      "efc__done": d._impl.efc__done.shape,
      "efc__ls_done": d._impl.efc__ls_done.shape,
      "efc__p0": d._impl.efc__p0.shape,
      "efc__lo": d._impl.efc__lo.shape,
      "efc__lo_alpha": d._impl.efc__lo_alpha.shape,
      "efc__hi": d._impl.efc__hi.shape,
      "efc__hi_alpha": d._impl.efc__hi_alpha.shape,
      "efc__lo_next": d._impl.efc__lo_next.shape,
      "efc__lo_next_alpha": d._impl.efc__lo_next_alpha.shape,
      "efc__hi_next": d._impl.efc__hi_next.shape,
      "efc__hi_next_alpha": d._impl.efc__hi_next_alpha.shape,
      "efc__mid": d._impl.efc__mid.shape,
      "efc__mid_alpha": d._impl.efc__mid_alpha.shape,
      "efc__cost_candidate": d._impl.efc__cost_candidate.shape,
      "efc__quad_total_candidate": d._impl.efc__quad_total_candidate.shape,
      "efc__u": d._impl.efc__u.shape,
      "efc__uu": d._impl.efc__uu.shape,
      "efc__uv": d._impl.efc__uv.shape,
      "efc__vv": d._impl.efc__vv.shape,
      "efc__condim": d._impl.efc__condim.shape,
      "sap_projection_lower": d._impl.sap_projection_lower.shape,
      "sap_projection_upper": d._impl.sap_projection_upper.shape,
      "sap_sort_index": d._impl.sap_sort_index.shape,
      "sap_range": d._impl.sap_range.shape,
      "collision_pair": d._impl.collision_pair.shape,
      "collision_pairid": d._impl.collision_pairid.shape,
      "collision_worldid": d._impl.collision_worldid.shape,
      "ncollision": d._impl.ncollision.shape,
      "cacc": d._impl.cacc.shape,
      "cfrc_int": d._impl.cfrc_int.shape,
      "cfrc_ext": d._impl.cfrc_ext.shape,
      "ten_length": d._impl.ten_length.shape,
      "ten_J": d._impl.ten_J.shape,
      "ten_wrapadr": d._impl.ten_wrapadr.shape,
      "ten_wrapnum": d._impl.ten_wrapnum.shape,
      "wrap_obj": d._impl.wrap_obj.shape,
      "wrap_xpos": d._impl.wrap_xpos.shape,
      "sensordata": d.sensordata.shape,
  }

  jf = ffi_helper.jax_callable_variadic_tuple(
      _forward_shim,
      num_outputs=120,
      output_dims=output_dims,
      vmap_method="expand_dims",
      graph_compatible=True,
  )
  out = jf(
      m.nv,
      m.nu,
      m.na,
      m.nbody,
      m.njnt,
      m.ngeom,
      m.nsite,
      m.ncam,
      m.nlight,
      m.neq,
      m.nmocap,
      m.ngravcomp,
      m.nM,
      m.ntendon,
      m._impl.nlsp,
      m.opt.timestep,
      m.opt.impratio,
      m.opt.tolerance,
      m.opt.ls_tolerance,
      m.opt.gravity,
      m.opt.cone,
      m.opt.solver,
      m.opt.iterations,
      m.opt.ls_iterations,
      m.opt.disableflags,
      m.opt.is_sparse,
      m.opt.ls_parallel,
      m.opt.wind,
      m.opt.density,
      m.opt.viscosity,
      m.stat.meaninertia,
      m.qpos0,
      m.qpos_spring,
      m._impl.qM_fullm_i,
      m._impl.qM_fullm_j,
      m._impl.qM_mulm_i,
      m._impl.qM_mulm_j,
      m._impl.qM_madr_ij,
      m._impl.qLD_updates,
      m._impl.M_rownnz,
      m._impl.M_rowadr,
      m._impl.mapM2M,
      m._impl.qM_tiles,
      m._impl.body_tree,
      m.body_parentid,
      m.body_rootid,
      m.body_jntnum,
      m.body_jntadr,
      m.body_dofnum,
      m.body_dofadr,
      m.body_pos,
      m.body_quat,
      m.body_ipos,
      m.body_iquat,
      m.body_mass,
      m.body_subtreemass,
      m._impl.subtree_mass,
      m.body_inertia,
      m.body_invweight0,
      m.body_gravcomp,
      m.jnt_type,
      m.jnt_qposadr,
      m.jnt_dofadr,
      m.jnt_bodyid,
      m.jnt_actfrclimited,
      m.jnt_solref,
      m.jnt_solimp,
      m.jnt_pos,
      m.jnt_axis,
      m.jnt_stiffness,
      m.jnt_range,
      m.jnt_actfrcrange,
      m.jnt_margin,
      m._impl.jnt_limited_slide_hinge_adr,
      m._impl.jnt_limited_ball_adr,
      m.jnt_actgravcomp,
      m.dof_bodyid,
      m.dof_jntid,
      m.dof_parentid,
      m.dof_Madr,
      m.dof_armature,
      m.dof_damping,
      m.dof_invweight0,
      m.dof_frictionloss,
      m.dof_solimp,
      m.dof_solref,
      m._impl.dof_tri_row,
      m._impl.dof_tri_col,
      m.geom_type,
      m.geom_bodyid,
      m.geom_rbound,
      m.geom_pos,
      m.geom_quat,
      m.geom_margin,
      m.site_bodyid,
      m.site_pos,
      m.site_quat,
      m.cam_mode,
      m.cam_bodyid,
      m.cam_targetbodyid,
      m.cam_pos,
      m.cam_quat,
      m.cam_poscom0,
      m.cam_pos0,
      m.cam_mat0,
      m.cam_fovy,
      m.cam_resolution,
      m.cam_sensorsize,
      m.cam_intrinsic,
      m.light_mode,
      m._impl.light_bodyid,
      m._impl.light_targetbodyid,
      m.light_pos,
      m.light_dir,
      m.light_poscom0,
      m.light_pos0,
      m.light_dir0,
      m.eq_obj1id,
      m.eq_obj2id,
      m.eq_objtype,
      m.eq_solref,
      m.eq_solimp,
      m.eq_data,
      m._impl.eq_connect_adr,
      m._impl.eq_wld_adr,
      m._impl.eq_jnt_adr,
      m._impl.eq_ten_adr,
      m._impl.actuator_moment_tiles_nv,
      m._impl.actuator_moment_tiles_nu,
      m.actuator_trntype,
      m.actuator_dyntype,
      m.actuator_gaintype,
      m.actuator_biastype,
      m.actuator_trnid,
      m.actuator_actadr,
      m.actuator_actnum,
      m.actuator_ctrllimited,
      m.actuator_forcelimited,
      m.actuator_dynprm,
      m.actuator_gainprm,
      m.actuator_biasprm,
      m.actuator_ctrlrange,
      m.actuator_forcerange,
      m.actuator_gear,
      m._impl.nxn_geom_pair,
      m._impl.nxn_pairid,
      m._impl.condim_max,
      m.tendon_adr,
      m.tendon_num,
      m._impl.tendon_limited_adr,
      m.tendon_solref_lim,
      m.tendon_solimp_lim,
      m.tendon_range,
      m.tendon_margin,
      m.tendon_length0,
      m.tendon_invweight0,
      m.wrap_objid,
      m.wrap_prm,
      m.wrap_type,
      m._impl.tendon_jnt_adr,
      m._impl.tendon_site_pair_adr,
      m._impl.ten_wrapadr_site,
      m._impl.ten_wrapnum_site,
      m._impl.wrap_jnt_adr,
      m._impl.wrap_site_adr,
      m._impl.wrap_site_pair_adr,
      m.sensor_type,
      m.sensor_datatype,
      m.sensor_objtype,
      m.sensor_objid,
      m.sensor_reftype,
      m.sensor_refid,
      m.sensor_adr,
      m.sensor_cutoff,
      m._impl.sensor_pos_adr,
      m._impl.sensor_vel_adr,
      m._impl.sensor_acc_adr,
      m._impl.sensor_subtree_vel,
      m._impl.sensor_rne_postconstraint,
      m._impl.mocap_bodyid,
      d._impl.nconmax,
      d._impl.njmax,
      d._impl.ncon,
      d.time,
      d.qpos,
      d.qvel,
      d.act,
      d.qacc_warmstart,
      d.ctrl,
      d.qfrc_applied,
      d.xfrc_applied,
      d.eq_active,
      d.mocap_pos,
      d.mocap_quat,
      d._impl.qLD,
      d._impl.qLDiagInv,
      d.qfrc_fluid,
      d.qacc_smooth,
      d._impl.contact__dist,
      d._impl.contact__pos,
      d._impl.contact__frame,
      d._impl.contact__includemargin,
      d._impl.contact__friction,
      d._impl.contact__solref,
      d._impl.contact__solreffriction,
      d._impl.contact__solimp,
      d._impl.contact__dim,
      d._impl.contact__geom,
      d._impl.contact__worldid,
      d._impl.efc__mv,
      d._impl.sap_cumulative_sum,
      d._impl.sap_segment_index,
  )
  d = d.tree_replace({
      "_impl.ne": out[0],
      "_impl.ne_connect": out[1],
      "_impl.ne_weld": out[2],
      "_impl.ne_jnt": out[3],
      "_impl.ne_ten": out[4],
      "_impl.nf": out[5],
      "_impl.nl": out[6],
      "_impl.nefc": out[7],
      "_impl.fluid_applied": out[8],
      "qacc": out[9],
      "act_dot": out[10],
      "xpos": out[11],
      "xquat": out[12],
      "xmat": out[13],
      "xipos": out[14],
      "ximat": out[15],
      "xanchor": out[16],
      "xaxis": out[17],
      "geom_xpos": out[18],
      "geom_xmat": out[19],
      "site_xpos": out[20],
      "site_xmat": out[21],
      "cam_xpos": out[22],
      "cam_xmat": out[23],
      "_impl.light_xpos": out[24],
      "_impl.light_xdir": out[25],
      "subtree_com": out[26],
      "_impl.cdof": out[27],
      "_impl.cinert": out[28],
      "_impl.actuator_length": out[29],
      "_impl.actuator_moment": out[30],
      "_impl.crb": out[31],
      "_impl.qM": out[32],
      "_impl.ten_velocity": out[33],
      "_impl.actuator_velocity": out[34],
      "cvel": out[35],
      "_impl.cdof_dot": out[36],
      "qfrc_bias": out[37],
      "_impl.qfrc_spring": out[38],
      "_impl.qfrc_damper": out[39],
      "qfrc_gravcomp": out[40],
      "qfrc_passive": out[41],
      "_impl.subtree_linvel": out[42],
      "_impl.subtree_angmom": out[43],
      "_impl.subtree_bodyvel": out[44],
      "actuator_force": out[45],
      "qfrc_actuator": out[46],
      "qfrc_smooth": out[47],
      "qfrc_constraint": out[48],
      "_impl.contact__efc_address": out[49],
      "_impl.efc__worldid": out[50],
      "_impl.efc__id": out[51],
      "_impl.efc__J": out[52],
      "_impl.efc__pos": out[53],
      "_impl.efc__margin": out[54],
      "_impl.efc__D": out[55],
      "_impl.efc__aref": out[56],
      "_impl.efc__frictionloss": out[57],
      "_impl.efc__force": out[58],
      "_impl.efc__Jaref": out[59],
      "_impl.efc__Ma": out[60],
      "_impl.efc__grad": out[61],
      "_impl.efc__grad_dot": out[62],
      "_impl.efc__Mgrad": out[63],
      "_impl.efc__search": out[64],
      "_impl.efc__search_dot": out[65],
      "_impl.efc__gauss": out[66],
      "_impl.efc__cost": out[67],
      "_impl.efc__prev_cost": out[68],
      "_impl.efc__solver_niter": out[69],
      "_impl.efc__active": out[70],
      "_impl.efc__gtol": out[71],
      "_impl.efc__jv": out[72],
      "_impl.efc__quad": out[73],
      "_impl.efc__quad_gauss": out[74],
      "_impl.efc__h": out[75],
      "_impl.efc__alpha": out[76],
      "_impl.efc__prev_grad": out[77],
      "_impl.efc__prev_Mgrad": out[78],
      "_impl.efc__beta": out[79],
      "_impl.efc__beta_num": out[80],
      "_impl.efc__beta_den": out[81],
      "_impl.efc__done": out[82],
      "_impl.efc__ls_done": out[83],
      "_impl.efc__p0": out[84],
      "_impl.efc__lo": out[85],
      "_impl.efc__lo_alpha": out[86],
      "_impl.efc__hi": out[87],
      "_impl.efc__hi_alpha": out[88],
      "_impl.efc__lo_next": out[89],
      "_impl.efc__lo_next_alpha": out[90],
      "_impl.efc__hi_next": out[91],
      "_impl.efc__hi_next_alpha": out[92],
      "_impl.efc__mid": out[93],
      "_impl.efc__mid_alpha": out[94],
      "_impl.efc__cost_candidate": out[95],
      "_impl.efc__quad_total_candidate": out[96],
      "_impl.efc__u": out[97],
      "_impl.efc__uu": out[98],
      "_impl.efc__uv": out[99],
      "_impl.efc__vv": out[100],
      "_impl.efc__condim": out[101],
      "_impl.sap_projection_lower": out[102],
      "_impl.sap_projection_upper": out[103],
      "_impl.sap_sort_index": out[104],
      "_impl.sap_range": out[105],
      "_impl.collision_pair": out[106],
      "_impl.collision_pairid": out[107],
      "_impl.collision_worldid": out[108],
      "_impl.ncollision": out[109],
      "_impl.cacc": out[110],
      "_impl.cfrc_int": out[111],
      "_impl.cfrc_ext": out[112],
      "_impl.ten_length": out[113],
      "_impl.ten_J": out[114],
      "_impl.ten_wrapadr": out[115],
      "_impl.ten_wrapnum": out[116],
      "_impl.wrap_obj": out[117],
      "_impl.wrap_xpos": out[118],
      "sensordata": out[119],
  })
  return d
